import Sidebar from "@/components/layout/Sidebar";
import "./globals.css";
import "@fortawesome/fontawesome-svg-core/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Sidebar />

        <div className="h-full min-h-screen pl-24 bg-zinc-100 dark:bg-gray-900 text-zinc-800 dark:text-gray-200">
          <div className="grid grid-cols-3 gap-4 p-8">
            <section className="col-span-3">{children}</section>
          </div>
        </div>
      </body>
    </html>
  );
}
